<a href="https://colab.research.google.com/github/chokyungjin0504/AIProgramming/blob/main/numpy_%EC%97%B0%EC%8A%B52_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

아래 문제들은 결과 출력까지 실행 후 ipynb  파일과 .py 파일로 제출  
print(b)의 결과가 다음과 같이 되는 code를 작성하시오..  
b는 a를 이용하여 정의 함.   

1.   
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]


In [ ]:
import numpy as np
a=np.arange(16).reshape(1, 16)

b = a[:, ::1]

print(a)
print(b)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]


2.   
[  [ 0  1  2  3  4  5  6  7]  
   [ 8  9 10 11 12 13 14 15]  ]


In [ ]:
import numpy as np
a = np.arange(16).reshape(2, 8)

b = a

print(a)
print(b)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


3.

[ [ [ 0  1]  
    [ 2  3]  
    [ 4  5]  
    [ 6  7]  
    [ 8  9]  
    [10 11]  
    [12 13]  
    [14 15]]  ]  

In [ ]:
import numpy as np

a = np.arange(16).reshape(8, 2)

b = np.reshape(a, (8, 2))

print(a)
print(b)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


4.

[ [[ 0]  
   [ 1]  
   [ 2]]  

 [ [ 3]  
   [ 4]  
   [ 5] ]  

 [ [ 6]  
   [ 7]  
   [ 8]  ]  

 [ [ 9]  
   [10]  
   [11] ] ]  


In [ ]:
import numpy as np
a = np.arange(12).reshape(4, 3)
b = np.reshape(a, (4, 3, 1))

print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0]
  [ 1]
  [ 2]]

 [[ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]]]


5. [8]  



In [ ]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[1:2, 3:]
print(b)

[[8]]
